services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - save_backend:/Sentinel1_images_processing/app/express-app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - save_frontend:/Sentinel1_images_processing/app/react-app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

volumes:
  save_backend:
  save_frontend:
